Implement title query

diff --git a/.github/workflows/devto_pipeline.yml b/.github/workflows/devto_pipeline.yml
--- a/.github/workflows/devto_pipeline.yml
+++ b/.github/workflows/devto_pipeline.yml
@@ -34,50 +34,60 @@ jobs:
     steps:
       # TODO cleanup this query mess
       - name: Get markdown files from ${{ github.repository}}
-        id: get-source-md-files
+        id: get-source-titles
         # TODO change to publish branch when implemented
         run: |
           IGNORED_FILES_JSON=$(jq -R -c 'split(",")' <<< "${{ vars.IGNORED_FILES }}")
+
           md_files_json=$(gh api repos/philnewm/blog-articles/git/trees/pages-debug?recursive=1 --jq '[.tree[].path | select(endswith(".md"))]')
-          md_files_json=$(echo $md_files_json | jq --argjson ignored "$IGNORED_FILES_JSON" 'map(select(. as $file | $ignored | index($file) | not))')
-          md_files_str=$(echo $md_files_json | jq -c)
+          filtered_md_files_json=$(echo $md_files_json | jq --argjson ignored "$IGNORED_FILES_JSON" 'map(select(. as $file | $ignored | index($file) | not))')
 
-          # TODO only keep basenames
+          # Convert JSON array to Bash array
+          mapfile -t md_files < <(echo "$filtered_md_files_json" | jq -r '.[]')
 
-          echo "source_files=$md_files_str" >> $GITHUB_OUTPUT
+          titles_json="[]"
+          for file in "${md_files[@]}"; do
+              title=$(gh api repos/philnewm/blog-articles/contents/"$file" --jq '.content' | base64 --decode | grep -m 1 '^# ' | sed 's/^# //')
+              if [[ -z "$title" ]]; then
+                  echo "::error::No title found for $file"
+                  exit 1
+              fi
+
+              titles_json=$(echo "$titles_json" | jq --arg title "$title" '. + [$title]')
+          done
+
+          echo "titles=$titles_json" >> $GITHUB_OUTPUT
         env:
           GH_TOKEN: ${{ github.token }}
 
       - name: Get article titles from dev.to
-        id: get-titles
+        id: get-target-titles
         run: |
           article_titles=$(curl -H "api-key: ${{ secrets.DEVTO_KEY }}" https://dev.to/api/articles/me/all | jq -c '.[].title')
           titles_str=$(echo $article_titles | jq -c)
 
-          echo "articles=$titles_str" >> $GITHUB_OUTPUT
+          echo "titles=$titles_str" >> $GITHUB_OUTPUT
 
       - name: Debug output
         run: |
-          echo "source_files=$(echo '${{ steps.get-source-md-files.outputs.source_files }}' | jq -r)"
-          echo "target_files=$(echo '${{ steps.get-target-md-files.outputs.target_files }}' | jq -r)"
+          echo "source_files=$(echo '${{ steps.get-source-titles.outputs.titles }}' | jq -r)"
+          echo "target_files=$(echo '${{ steps.get-target-titles.outputs.titles }}' | jq -r)"
 
-      - name: Compare files
-        id: compare-files
+      - name: Compare titles
+        id: compare-titles
         run: |
-          source_files=$(echo '${{ steps.get-source-md-files.outputs.source_files }}' | jq -r)
-          target_files=$(echo '${{ steps.get-target-md-files.outputs.target_files }}' | jq -r)
+          source_titles=$(echo '${{ steps.get-source-titles.outputs.titles }}' | jq -r)
+          target_titles=$(echo '${{ steps.get-target-titles.outputs.titles }}' | jq -r)
 
-          files_added=$(echo $source_files $target_files | jq -s -c '.[0] - .[1]')
-          files_removed=$(echo $source_files $target_files | jq -s -c '.[1] - .[0]')
+          titles_added=$(echo $source_titles $target_titles | jq -s -c '.[0] - .[1]')
+          titles_removed=$(echo $source_titles $target_titles | jq -s -c '.[1] - .[0]')
 
-          echo "files_added=$files_added" >> $GITHUB_OUTPUT
-          echo "files_removed=$files_removed" >> $GITHUB_OUTPUT
+          echo "titles_added=$files_added" >> $GITHUB_OUTPUT
+          echo "titles_removed=$files_removed" >> $GITHUB_OUTPUT
 
           base_url="https://raw.githubusercontent.com/${{ github.repository }}/refs/heads/${{ github.ref_name }}/"
           files_csv=$(echo "$files_added" | jq -r --arg base "$base_url" '[.[] | $base + .] | join(",")')
           echo "files_csv=$files_csv" >> $GITHUB_OUTPUT
-
-          # https://raw.githubusercontent.com/philnewm/blog-articles/refs/heads/pages-debug/
 
       - name: Debug output
         run: |
